Core/Controllers/TeamController.cs
using Core.Modeles;
using Core.ViewModeles;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Core.Controllers
{

   
    public class TeamController:Controller
    {
        public readonly ITeamMembersRepository _TeamMemberModele;
        public readonly IWebHostEnvironment _Webenvironment;

        public TeamController(ITeamMembersRepository modeles, IWebHostEnvironment Webenvironment)
        {
            _TeamMemberModele = modeles;
            _Webenvironment = Webenvironment;
        }

        public ViewResult Details(int id)
        {
            TeamMember memberInfo = _TeamMemberModele.GetMember(id);
            if (memberInfo == null)
            {
                ViewBag.Message = $"There is no member with id: {id} on the system";
                ViewBag.Title = "Not Found";
                return View("NotFound");
                
            }

            TeamDetailsViewModel modelMember = new()
            {
                Member = memberInfo,
                PageTitle = "Team Member Details"

            };

            return View(modelMember);

        }


        [AllowAnonymous]
        public ViewResult Index()
        {
            TeamIndexViewModel listMember = new()
            {
                ListTeamMembers = _TeamMemberModele.GetAllMembers(),
                PageTitle = "List Of Members",
            };

            return View(listMember);
        }


        [HttpGet]
        public IActionResult Create()
        {
         return View();
        }


        [HttpPost]
        public IActionResult Create(CreateMemberViewModel model)
        {
            
            string uniqueString = "";
            if(ModelState.IsValid)
            {

                if(model.Photo!=null)
                {
                    uniqueString = SavePhoto(model);
                }

                TeamMember newMember = new()
                {
                    Name = model.Name,
                    Position = model.Position,
                    Country = model.Country,
                    Phone = model.Phone,
                    Summary = model.Summary,
                    Nationality = model.Nationality,
                    PhotoPath = uniqueString
                };

                _TeamMemberModele.Add(newMember);
                return RedirectToAction("details", new { id = newMember.Id });
            }
            else
            {
                //return RedirectToAction("list");
               return View(model);
            }
         
           //return View();
        }

        private string SavePhoto(CreateMemberViewModel model)
        {
            string uniqueString;
            string folderName = Path.Combine(_Webenvironment.WebRootPath, "images");
            uniqueString = Guid.NewGuid().ToString() + "_" + model.Photo.FileName;
            string filePath = Path.Combine(folderName, uniqueString);
           
            using(var fileStreamed = new FileStream(filePath, FileMode.Create))
            {
                model.Photo.CopyTo(fileStreamed);
            }
            

            return uniqueString;
        }


        [HttpGet]
        public ViewResult Edit(int id)
        {
            TeamMember editedMember = _TeamMemberModele.GetMember(id);
            EditMemberViewModel toEditMember = new()
            {
                //Id = employee.Id.Value,
                Name = editedMember.Name,
                Position = editedMember.Position,
                Country = editedMember.Country,
                Phone= editedMember.Phone,
                Summary = editedMember.Summary,
                Nationality = editedMember.Nationality,
                CurrentPhotoPath = editedMember.PhotoPath,


            };
           
            return View(toEditMember); 
        }



        [HttpPost]
        public IActionResult Edit(EditMemberViewModel model)
        {
           
            if (ModelState.IsValid)
            {
                TeamMember updatedMember = _TeamMemberModele.GetMember(model.Id);
                updatedMember.Name = model.Name;
                updatedMember.Position = model.Position;
                updatedMember.Country = model.Country;
                updatedMember.Phone = model.Phone;
                updatedMember.Summary = model.Summary;
                updatedMember.Nationality = model.Nationality;
                if (model.Photo != null)
                {
                    if(model.CurrentPhotoPath != null)
                    {
                        string currentPath= Path.Combine(_Webenvironment.WebRootPath, "images", model.CurrentPhotoPath);
                        System.IO.File.Delete(currentPath);
                    }
                    updatedMember.PhotoPath = SavePhoto(model);
                }
                _TeamMemberModele.Update(updatedMember);
                return RedirectToAction("index");
            }
            else
            {
                return View(model);
            }
        }


    }
}

Core/Views/Shared/NotFound.cshtml
    <div class="divContainer text-center mt-3 radiusMode">
 <br />
        <h1 class="text-danger mycard">@ViewBag.Title</h1>
      
        <h3 class="text-danger">@ViewBag.Message</h3>
     
        <a asp-action="index" asp-controller="Home" class="btn btn-outline-success mb-5" style="width:auto">Click Here to View List</a>
    </div>

Core/Views/Shared/_Layout.cshtml
@inject SignInManager<IdentityUser> signInManage;
@inject IAuthorizationService _userAuthorization;

@{#pragma warning disable CS8602}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/jquery-validate/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
    <link href="~/lib/bootstrap/css/bootstrap.css" rel="stylesheet" />
    <script src="~/lib/bootstrap/js/bootstrap.js"></script>
    <link href="~/my_css/mystyle.css" rel="stylesheet" />
    <title>@ViewBag.Title</title>
</head>

<body>
    <div class="manDiv">
        <div class="container radiusInput bTransp">
            <nav class="navbar navbar-expand-sm bg-dark navbar-dark radiusMode mt-1 navHover">

                <a class="navbar-brand" asp-action="Welcome" asp-controller="Home">
                    <img src="~/images/kailogo.png" height="40" width="40" class="radiusMode" asp-append-version="true" />
                </a>

                <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#collapsibleNavbar">
                    <span class="navbar-toggler-icon"> </span>
                </button>
                <div class="collapse navbar-collapse" id="collapsibleNavbar">
                    <ul class="navbar-nav">

                        <li class="nav-item">
                            <a asp-action="Welcome" asp-controller="Home" class="nav-link">Home</a>
                        </li>



                        <li class="nav-item dropdown navDropMenu">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true"
                               aria-expanded="false">
                                Team
                            </a>

                            <div class="dropdown-menu myCard" aria-labelledby="navbarDropdownMenuLink" style="border:1px solid sienna">
                                <a asp-action="index" asp-controller="Team" class="dropdown-item">Consult</a>
                                @if (signInManage.IsSignedIn(User) && User.IsInRole("Admin") || signInManage.IsSignedIn(User) && User.IsInRole("Super Admin")
                                || signInManage.IsSignedIn(User) && (await _userAuthorization.AuthorizeAsync(User, "AllAllowedPolicy")).Succeeded)
                                {
                                    <a asp-action="Create" asp-controller="Team" class="dropdown-item">Create</a>
 
                                }
                               
                            </div>
                        </li>


                        <li class="nav-item dropdown navDropMenu">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true"
                               aria-expanded="false">
                                Gallery
                            </a>

                            <div class="dropdown-menu myCard" aria-labelledby="navbarDropdownMenuLink" style="border:1px solid sienna">
                                <a href="#" class="dropdown-item">Gallery Photos</a>
                                @if (signInManage.IsSignedIn(User) && User.IsInRole("Admin") || signInManage.IsSignedIn(User) && User.IsInRole("Super Admin")
                                || signInManage.IsSignedIn(User) && (await _userAuthorization.AuthorizeAsync(User, "AllAllowedPolicy")).Succeeded)
                                {
                                    <a href="#" class="dropdown-item">Add Photo</a>
                                }
                                <a href="#" class="dropdown-item">Gallery Videos</a>
                            </div>
                        </li>

                        @if (signInManage.IsSignedIn(User))
                        {
                            <li class="nav-item dropdown navDropMenu">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true"
                                   aria-expanded="false">
                                    Manage
                                </a>

                                <div class="dropdown-menu myCard" aria-labelledby="navbarDropdownMenuLink" style="border:1px solid sienna">
                                    @if (signInManage.IsSignedIn(User) && User.IsInRole("Admin") || signInManage.IsSignedIn(User) && User.IsInRole("Super Admin")
                                   || signInManage.IsSignedIn(User) && (await _userAuthorization.AuthorizeAsync(User, "AllAllowedPolicy")).Succeeded)
                                    {
                                        <a asp-action="listUsers" asp-controller="Administration" class="dropdown-item">Users</a>
                                        <a asp-action="listRoles" asp-controller="Administration" class="dropdown-item">Roles</a>
                                    }
                                    <a asp-action="ChangePassword" asp-controller="Account" class="dropdown-item">Password</a>
                                </div>
                            </li>
                        }
                    </ul>

                    <ul class="navbar-nav ml-auto">
                        @if (@signInManage.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <form method="post" asp-action="logout" asp-controller="account">
                                    <button type="submit" class="nav-link btn btn-link py-0"
                                            style="width:auto;">
                                        Logout - @User.Identity.Name
                                    </button>
                                </form>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a asp-action="register" asp-controller="account" class="nav-link">Register</a>
                            </li>

                            <li class="nav-item">
                                <a asp-action="login" asp-controller="account" class="nav-link">Login</a>
                            </li>
                        }
                    </ul>
                </div>
            </nav>
            <div>
                @RenderBody()
            </div>
            @{
                if (IsSectionDefined("Scripts"))
                {
                    RenderSection("Scripts", required: true);
                }
            }

            <footer class="radiusMode">
                <h1 class="text-center">Footer Code Here</h1>
            </footer>
        
        </div>
    </div>
 
</body>
</html>